// Code generated by the Encore v1.57.5 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-shipment-tracker-ysci.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the shipment-tracker-ysci Encore application.
 */
export default class Client {
    public readonly auth: auth.ServiceClient
    public readonly automation: automation.ServiceClient
    public readonly invoicing: invoicing.ServiceClient
    public readonly quotes: quotes.ServiceClient
    public readonly shipments: shipments.ServiceClient
    public readonly warehouse: warehouse.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.auth = new auth.ServiceClient(base)
        this.automation = new automation.ServiceClient(base)
        this.invoicing = new invoicing.ServiceClient(base)
        this.quotes = new quotes.ServiceClient(base)
        this.shipments = new shipments.ServiceClient(base)
        this.warehouse = new warehouse.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
}

export namespace auth {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.authLogin = this.authLogin.bind(this)
            this.authMe = this.authMe.bind(this)
        }

        public async authLogin(params: controllers.AuthLoginRequest): Promise<controllers.AuthLoginResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/auth/login`, JSON.stringify(params))
            return await resp.json() as controllers.AuthLoginResponse
        }

        public async authMe(params: controllers.AuthMeRequest): Promise<controllers.AuthMeResponse> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                authorization: params.authorization,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/auth/me`, undefined, {headers})
            return await resp.json() as controllers.AuthMeResponse
        }
    }
}

export namespace automation {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.automationLogs = this.automationLogs.bind(this)
            this.automationTrigger = this.automationTrigger.bind(this)
        }

        public async automationLogs(shipmentId: string): Promise<controllers.AutomationLogsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/automation/${encodeURIComponent(shipmentId)}/logs`)
            return await resp.json() as controllers.AutomationLogsResponse
        }

        public async automationTrigger(params: controllers.AutomationTriggerRequest): Promise<controllers.AutomationTriggerResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/automation/trigger`, JSON.stringify(params))
            return await resp.json() as controllers.AutomationTriggerResponse
        }
    }
}

export namespace invoicing {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.invoicingAddCharge = this.invoicingAddCharge.bind(this)
            this.invoicingDeleteCharge = this.invoicingDeleteCharge.bind(this)
            this.invoicingGenerate = this.invoicingGenerate.bind(this)
            this.invoicingGet = this.invoicingGet.bind(this)
            this.invoicingUpdateCharge = this.invoicingUpdateCharge.bind(this)
            this.invoicingUpsertBillingOverride = this.invoicingUpsertBillingOverride.bind(this)
            this.invoicingUpsertBillingSettings = this.invoicingUpsertBillingSettings.bind(this)
            this.invoicingUpsertCost = this.invoicingUpsertCost.bind(this)
        }

        public async invoicingAddCharge(shipmentId: string, params: controllers.AddChargeRequest): Promise<controllers.AddChargeResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/invoicing/${encodeURIComponent(shipmentId)}/additional`, JSON.stringify(params))
            return await resp.json() as controllers.AddChargeResponse
        }

        public async invoicingDeleteCharge(shipmentId: string, chargeId: string): Promise<controllers.DeleteChargeResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/invoicing/${encodeURIComponent(shipmentId)}/additional/${encodeURIComponent(chargeId)}`)
            return await resp.json() as controllers.DeleteChargeResponse
        }

        public async invoicingGenerate(shipmentId: string, params: controllers.GenerateInvoiceRequest): Promise<controllers.GenerateInvoiceResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/invoicing/${encodeURIComponent(shipmentId)}/generate`, JSON.stringify(params))
            return await resp.json() as controllers.GenerateInvoiceResponse
        }

        public async invoicingGet(shipmentId: string): Promise<controllers.InvoicingGetResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/invoicing/${encodeURIComponent(shipmentId)}`)
            return await resp.json() as controllers.InvoicingGetResponse
        }

        public async invoicingUpdateCharge(shipmentId: string, chargeId: string, params: controllers.UpdateChargeRequest): Promise<controllers.UpdateChargeResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PATCH", `/invoicing/${encodeURIComponent(shipmentId)}/additional/${encodeURIComponent(chargeId)}`, JSON.stringify(params))
            return await resp.json() as controllers.UpdateChargeResponse
        }

        public async invoicingUpsertBillingOverride(shipmentId: string, params: controllers.UpsertBillingOverrideRequest): Promise<controllers.UpsertBillingOverrideResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/invoicing/${encodeURIComponent(shipmentId)}/billing/overrides`, JSON.stringify(params))
            return await resp.json() as controllers.UpsertBillingOverrideResponse
        }

        public async invoicingUpsertBillingSettings(shipmentId: string, params: controllers.UpsertBillingSettingsRequest): Promise<controllers.UpsertBillingSettingsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/invoicing/${encodeURIComponent(shipmentId)}/billing`, JSON.stringify(params))
            return await resp.json() as controllers.UpsertBillingSettingsResponse
        }

        public async invoicingUpsertCost(shipmentId: string, params: controllers.UpsertCostRequest): Promise<controllers.UpsertCostResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/invoicing/${encodeURIComponent(shipmentId)}/costs`, JSON.stringify(params))
            return await resp.json() as controllers.UpsertCostResponse
        }
    }
}

export namespace quotes {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.quoteAllocateRef = this.quoteAllocateRef.bind(this)
            this.quoteCreate = this.quoteCreate.bind(this)
            this.quoteDelete = this.quoteDelete.bind(this)
            this.quoteGet = this.quoteGet.bind(this)
            this.quoteList = this.quoteList.bind(this)
            this.quoteUpdate = this.quoteUpdate.bind(this)
        }

        public async quoteAllocateRef(quoteNumber: string): Promise<controllers.QuoteAllocateRefResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/quotes/${encodeURIComponent(quoteNumber)}/allocate-ref`)
            return await resp.json() as controllers.QuoteAllocateRefResponse
        }

        public async quoteCreate(params: controllers.QuoteCreateRequest): Promise<controllers.QuoteCreateResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/quotes`, JSON.stringify(params))
            return await resp.json() as controllers.QuoteCreateResponse
        }

        public async quoteDelete(quoteNumber: string): Promise<controllers.QuoteDeleteResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/quotes/${encodeURIComponent(quoteNumber)}`)
            return await resp.json() as controllers.QuoteDeleteResponse
        }

        public async quoteGet(quoteNumber: string): Promise<controllers.QuoteGetResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/quotes/${encodeURIComponent(quoteNumber)}`)
            return await resp.json() as controllers.QuoteGetResponse
        }

        public async quoteList(params: controllers.QuoteListRequest): Promise<controllers.QuoteListResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:         params.limit === undefined ? undefined : String(params.limit),
                offset:        params.offset === undefined ? undefined : String(params.offset),
                sortDirection: params.sortDirection === undefined ? undefined : String(params.sortDirection),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/quotes`, undefined, {query})
            return await resp.json() as controllers.QuoteListResponse
        }

        public async quoteUpdate(quoteNumber: string, params: controllers.QuoteUpdateRequest): Promise<controllers.QuoteUpdateResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PATCH", `/quotes/${encodeURIComponent(quoteNumber)}`, JSON.stringify(params))
            return await resp.json() as controllers.QuoteUpdateResponse
        }
    }
}

export namespace shipments {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.attachmentCreate = this.attachmentCreate.bind(this)
            this.attachmentDelete = this.attachmentDelete.bind(this)
            this.attachmentList = this.attachmentList.bind(this)
            this.commentCreate = this.commentCreate.bind(this)
            this.commentDelete = this.commentDelete.bind(this)
            this.commentList = this.commentList.bind(this)
            this.shipmentCreate = this.shipmentCreate.bind(this)
            this.shipmentDelete = this.shipmentDelete.bind(this)
            this.shipmentGet = this.shipmentGet.bind(this)
            this.shipmentLinkMasterJob = this.shipmentLinkMasterJob.bind(this)
            this.shipmentList = this.shipmentList.bind(this)
            this.shipmentUnlinkMasterJob = this.shipmentUnlinkMasterJob.bind(this)
            this.shipmentUpdate = this.shipmentUpdate.bind(this)
            this.taskList = this.taskList.bind(this)
            this.taskUpsert = this.taskUpsert.bind(this)
        }

        public async attachmentCreate(shipmentId: string, params: controllers.AttachmentCreateRequest): Promise<controllers.AttachmentCreateResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/shipments/${encodeURIComponent(shipmentId)}/attachments`, JSON.stringify(params))
            return await resp.json() as controllers.AttachmentCreateResponse
        }

        public async attachmentDelete(shipmentId: string, attachmentId: string): Promise<controllers.AttachmentDeleteResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/shipments/${encodeURIComponent(shipmentId)}/attachments/${encodeURIComponent(attachmentId)}`)
            return await resp.json() as controllers.AttachmentDeleteResponse
        }

        public async attachmentList(shipmentId: string): Promise<controllers.AttachmentListResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/shipments/${encodeURIComponent(shipmentId)}/attachments`)
            return await resp.json() as controllers.AttachmentListResponse
        }

        public async commentCreate(shipmentId: string, params: controllers.CommentCreateRequest): Promise<controllers.CommentCreateResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/shipments/${encodeURIComponent(shipmentId)}/comments`, JSON.stringify(params))
            return await resp.json() as controllers.CommentCreateResponse
        }

        public async commentDelete(shipmentId: string, commentId: string): Promise<controllers.CommentDeleteResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/shipments/${encodeURIComponent(shipmentId)}/comments/${encodeURIComponent(commentId)}`)
            return await resp.json() as controllers.CommentDeleteResponse
        }

        public async commentList(shipmentId: string): Promise<controllers.CommentListResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/shipments/${encodeURIComponent(shipmentId)}/comments`)
            return await resp.json() as controllers.CommentListResponse
        }

        public async shipmentCreate(params: controllers.ShipmentCreateRequest): Promise<controllers.ShipmentCreateResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/shipments`, JSON.stringify(params))
            return await resp.json() as controllers.ShipmentCreateResponse
        }

        public async shipmentDelete(shipmentId: string): Promise<controllers.ShipmentDeleteResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/shipments/${encodeURIComponent(shipmentId)}`)
            return await resp.json() as controllers.ShipmentDeleteResponse
        }

        public async shipmentGet(shipmentId: string): Promise<controllers.ShipmentGetResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/shipments/${encodeURIComponent(shipmentId)}`)
            return await resp.json() as controllers.ShipmentGetResponse
        }

        public async shipmentLinkMasterJob(shipmentId: string, params: controllers.LinkMasterJobRequest): Promise<controllers.LinkMasterJobResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/shipments/${encodeURIComponent(shipmentId)}/master-job`, JSON.stringify(params))
            return await resp.json() as controllers.LinkMasterJobResponse
        }

        public async shipmentList(params: controllers.ShipmentListRequest): Promise<controllers.ShipmentListResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:         params.limit === undefined ? undefined : String(params.limit),
                offset:        params.offset === undefined ? undefined : String(params.offset),
                sortDirection: params.sortDirection === undefined ? undefined : String(params.sortDirection),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/shipments`, undefined, {query})
            return await resp.json() as controllers.ShipmentListResponse
        }

        public async shipmentUnlinkMasterJob(shipmentId: string): Promise<controllers.UnlinkMasterJobResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/shipments/${encodeURIComponent(shipmentId)}/master-job`)
            return await resp.json() as controllers.UnlinkMasterJobResponse
        }

        public async shipmentUpdate(shipmentId: string, params: controllers.ShipmentUpdateRequest): Promise<controllers.ShipmentUpdateResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PATCH", `/shipments/${encodeURIComponent(shipmentId)}`, JSON.stringify(params))
            return await resp.json() as controllers.ShipmentUpdateResponse
        }

        public async taskList(shipmentId: string): Promise<controllers.TaskListResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/shipments/${encodeURIComponent(shipmentId)}/tasks`)
            return await resp.json() as controllers.TaskListResponse
        }

        public async taskUpsert(shipmentId: string, params: controllers.TaskUpsertRequest): Promise<controllers.TaskUpsertResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/shipments/${encodeURIComponent(shipmentId)}/tasks`, JSON.stringify(params))
            return await resp.json() as controllers.TaskUpsertResponse
        }
    }
}

export namespace warehouse {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.warehouseCreate = this.warehouseCreate.bind(this)
            this.warehouseDelete = this.warehouseDelete.bind(this)
            this.warehouseList = this.warehouseList.bind(this)
            this.warehouseUpdate = this.warehouseUpdate.bind(this)
        }

        public async warehouseCreate(params: controllers.WarehouseCreateRequest): Promise<controllers.WarehouseCreateResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/warehouse`, JSON.stringify(params))
            return await resp.json() as controllers.WarehouseCreateResponse
        }

        public async warehouseDelete(taskId: string): Promise<controllers.WarehouseDeleteResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/warehouse/${encodeURIComponent(taskId)}`)
            return await resp.json() as controllers.WarehouseDeleteResponse
        }

        public async warehouseList(params: controllers.WarehouseListRequest): Promise<controllers.WarehouseListResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                shipmentId: params.shipmentId,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/warehouse`, undefined, {query})
            return await resp.json() as controllers.WarehouseListResponse
        }

        public async warehouseUpdate(taskId: string, params: controllers.WarehouseUpdateRequest): Promise<controllers.WarehouseUpdateResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PATCH", `/warehouse/${encodeURIComponent(taskId)}`, JSON.stringify(params))
            return await resp.json() as controllers.WarehouseUpdateResponse
        }
    }
}

export namespace controllers {
    export interface AddChargeRequest {
        invoiceNumber?: string
        vendor?: string
        description?: string
        estAmount?: string
        estCurrency?: string
        realAmount?: string
        realCurrency?: string
        sortOrder?: number
    }

    export interface AddChargeResponse {
        charge: interfaces.AdditionalChargeItem
    }

    export interface AttachmentCreateRequest {
        fileName: string
        fileSize: number
        fileType: string
        storageKey?: string
    }

    export interface AttachmentCreateResponse {
        attachment: interfaces.AttachmentItem
    }

    export interface AttachmentDeleteResponse {
        ok: boolean
    }

    export interface AttachmentListResponse {
        attachments: interfaces.AttachmentItem[]
    }

    export interface AuthLoginRequest {
        email: string
        password: string
    }

    export interface AuthLoginResponse {
        token: string
        user: services.AuthUserInfo
    }

    export interface AuthMeRequest {
        authorization: string
    }

    export interface AuthMeResponse {
        user: services.AuthUserInfo
    }

    export interface AutomationLogsResponse {
        logs: interfaces.AutomationLogItem[]
    }

    export interface AutomationTriggerRequest {
        shipmentId: string
        column: string
        oldValue: string
        newValue: string
        triggeredById?: string
        shipmentData?: { [key: string]: string }
    }

    export interface AutomationTriggerResponse {
        actions: string[]
        logs: interfaces.AutomationLogItem[]
    }

    export interface CommentCreateRequest {
        authorId: string
        message: string
    }

    export interface CommentCreateResponse {
        comment: interfaces.CommentItem
    }

    export interface CommentDeleteResponse {
        ok: boolean
    }

    export interface CommentListResponse {
        comments: interfaces.CommentItem[]
    }

    export interface DeleteChargeResponse {
        ok: boolean
    }

    export interface GenerateInvoiceRequest {
        jobNumber: string
        invoiceType: string
        billingCurrency: string
        totalAmount: string
    }

    export interface GenerateInvoiceResponse {
        invoice: interfaces.GeneratedInvoiceItem
    }

    export interface InvoicingGetResponse {
        costs: interfaces.InvoiceCostItem[]
        additionalCharges: interfaces.AdditionalChargeItem[]
        billingSettings: interfaces.BillingSettingsItem | null
        billingOverrides: interfaces.BillingOverrideItem[]
        generatedInvoices: interfaces.GeneratedInvoiceItem[]
    }

    export interface LinkMasterJobRequest {
        mczNumber: string
    }

    export interface LinkMasterJobResponse {
        shipment: interfaces.ShipmentItem
    }

    export interface QuoteAllocateRefResponse {
        ref: string
    }

    export interface QuoteCreateRequest {
        quoteNumber: string
        data?: any
        terms?: string
    }

    export interface QuoteCreateResponse {
        quote: interfaces.QuoteItem
    }

    export interface QuoteDeleteResponse {
        ok: boolean
    }

    export interface QuoteGetResponse {
        quote: interfaces.QuoteItem
    }

    export interface QuoteListRequest {
        limit?: number
        offset?: number
        sortDirection?: "asc" | "desc"
    }

    export interface QuoteListResponse {
        pagination: {
            total: number
            offset: number
            limit: number
        }
        data: interfaces.QuoteItem[]
    }

    export interface QuoteUpdateRequest {
        data?: any
        terms?: string
    }

    export interface QuoteUpdateResponse {
        quote: interfaces.QuoteItem
    }

    export interface ShipmentCreateRequest {
        jobNumber: string
        shipper?: string
        consignee?: string
        pol?: string
        pod?: string
        destination?: string
        tradeDirection?: string
        loadType?: string
        status?: string
        customsStatus?: string
        vessel?: string
        voyage?: string
        shippingLine?: string
        bookingNumber?: string
        containerNumber?: string
        personalReference?: string
        agent?: string
        hsCode?: string
        cargoDescription?: string
        incotermOrigin?: string
        incotermDestination?: string
        houseBolNumber?: string
        masterBolNumber?: string
        houseBolType?: string
        masterBolType?: string
        pcs?: string
        totalWeightTons?: string
        totalVolumeCbm?: string
        cargoOrigin?: string
        commercialInvoiceValue?: string
        extra?: { [key: string]: string }
    }

    export interface ShipmentCreateResponse {
        shipment: interfaces.ShipmentItem
    }

    export interface ShipmentDeleteResponse {
        ok: boolean
    }

    export interface ShipmentGetResponse {
        shipment: interfaces.ShipmentItem
    }

    export interface ShipmentListRequest {
        limit?: number
        offset?: number
        sortDirection?: "asc" | "desc"
    }

    export interface ShipmentListResponse {
        pagination: {
            total: number
            offset: number
            limit: number
        }
        data: interfaces.ShipmentItem[]
    }

    export interface ShipmentUpdateRequest {
        shipper?: string
        consignee?: string
        pol?: string
        pod?: string
        destination?: string
        tradeDirection?: string
        loadType?: string
        status?: string
        customsStatus?: string
        vessel?: string
        voyage?: string
        shippingLine?: string
        bookingNumber?: string
        containerNumber?: string
        personalReference?: string
        agent?: string
        hsCode?: string
        cargoDescription?: string
        incotermOrigin?: string
        incotermDestination?: string
        houseBolNumber?: string
        masterBolNumber?: string
        houseBolType?: string
        masterBolType?: string
        pcs?: string
        totalWeightTons?: string
        totalVolumeCbm?: string
        cargoOrigin?: string
        commercialInvoiceValue?: string
        extra?: { [key: string]: string }
    }

    export interface ShipmentUpdateResponse {
        shipment: interfaces.ShipmentItem
    }

    export interface TaskListResponse {
        tasks: interfaces.TaskItem[]
    }

    export interface TaskUpsertRequest {
        taskKey: string
        completed: boolean
        completedById?: string
    }

    export interface TaskUpsertResponse {
        task: interfaces.TaskItem
    }

    export interface UnlinkMasterJobResponse {
        shipment: interfaces.ShipmentItem
    }

    export interface UpdateChargeRequest {
        invoiceNumber?: string
        vendor?: string
        description?: string
        estAmount?: string
        estCurrency?: string
        realAmount?: string
        realCurrency?: string
    }

    export interface UpdateChargeResponse {
        charge: interfaces.AdditionalChargeItem
    }

    export interface UpsertBillingOverrideRequest {
        rowKey: string
        billingAmount: string
    }

    export interface UpsertBillingOverrideResponse {
        override: interfaces.BillingOverrideItem
    }

    export interface UpsertBillingSettingsRequest {
        billingCurrency?: string
        roe?: string
        quoteRef?: string
    }

    export interface UpsertBillingSettingsResponse {
        billingSettings: interfaces.BillingSettingsItem
    }

    export interface UpsertCostRequest {
        category: string
        estAmount?: string
        estCurrency?: string
        realAmount?: string
        realCurrency?: string
        invoiceNumber?: string
        vendor?: string
    }

    export interface UpsertCostResponse {
        cost: interfaces.InvoiceCostItem
    }

    export interface WarehouseCreateRequest {
        taskId: string
        shipmentId?: string
    }

    export interface WarehouseCreateResponse {
        task: interfaces.WarehouseTaskItem
    }

    export interface WarehouseDeleteResponse {
        ok: boolean
    }

    export interface WarehouseListRequest {
        shipmentId?: string
    }

    export interface WarehouseListResponse {
        tasks: interfaces.WarehouseTaskItem[]
    }

    export interface WarehouseUpdateRequest {
        type?: string
        priority?: string
        status?: string
        assignee?: string
        dueDate?: string
        cargo?: string
        weight?: string
        notes?: string
        data?: any
    }

    export interface WarehouseUpdateResponse {
        task: interfaces.WarehouseTaskItem
    }
}

export namespace interfaces {
    export interface AdditionalChargeItem {
        id: string
        shipmentId: string
        invoiceNumber: string
        vendor: string
        description: string
        estAmount: string | null
        estCurrency: string
        realAmount: string | null
        realCurrency: string
        sortOrder: number
    }

    export interface AttachmentItem {
        id: string
        shipmentId: string
        fileName: string
        fileSize: number
        fileType: string
        storageKey: string
        createdAt: string
    }

    export interface AutomationLogItem {
        id: string
        shipmentId: string
        ruleName: string
        action: string
        details: any
        triggeredById: string | null
        createdAt: string
    }

    export interface BillingOverrideItem {
        id: string
        shipmentId: string
        rowKey: string
        billingAmount: string | null
    }

    export interface BillingSettingsItem {
        id: string
        shipmentId: string
        billingCurrency: string
        roe: string
        quoteRef: string
    }

    export interface CommentItem {
        id: string
        shipmentId: string
        authorId: string
        message: string
        createdAt: string
    }

    export interface GeneratedInvoiceItem {
        id: string
        shipmentId: string
        invoiceNumber: string
        invoiceType: string
        billingCurrency: string
        totalAmount: string
        createdAt: string
    }

    export interface InvoiceCostItem {
        id: string
        shipmentId: string
        category: string
        estAmount: string | null
        estCurrency: string
        realAmount: string | null
        realCurrency: string
        invoiceNumber: string
        vendor: string
    }

    export interface QuoteItem {
        id: string
        quoteNumber: string
        data: any
        terms: string
        createdAt: string
        updatedAt: string
    }

    export interface ShipmentItem {
        id: string
        jobNumber: string
        shipper: string
        consignee: string
        personalReference: string
        containerNumber: string
        bookingNumber: string
        loadType: string
        shippingLine: string
        pol: string
        pod: string
        destination: string
        hsCode: string
        cargoDescription: string
        houseBolNumber: string
        masterBolNumber: string
        houseBolType: string
        masterBolType: string
        vessel: string
        voyage: string
        pcs: string
        totalWeightTons: string | null
        totalVolumeCbm: string | null
        cargoOrigin: string
        countryCode: string
        origin: string
        estimatedDeparture: string | null
        estimatedArrival: string | null
        tradeDirection: string
        agent: string
        incotermOrigin: string
        incotermDestination: string
        commercialInvoiceValue: string | null
        status: string
        customsStatus: string
        masterJobId: string | null
        masterJobMczNumber: string | null
        containers: any
        extra: { [key: string]: string } | null
        createdAt: string
        updatedAt: string
    }

    export interface TaskItem {
        id: string
        shipmentId: string
        taskKey: string
        completed: boolean
        completedAt: string | null
        completedById: string | null
    }

    export interface WarehouseTaskItem {
        id: string
        taskId: string
        shipmentId: string | null
        type: string
        priority: string
        status: string
        assignee: string
        dueDate: string
        cargo: string
        weight: string
        notes: string
        data: any
        createdAt: string
    }
}

export namespace services {
    export interface AuthUserInfo {
        id: string
        email: string
        displayName: string
        role: string
    }
}



function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "method" | "body" | "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}


// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "shipment-tracker-ysci-Generated-TS-Client (Encore/v1.57.5)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(method: string, path: string, body?: RequestInit["body"], params?: CallParameters): Promise<Response> {
        return this.callAPI(method, path, body, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(method: string, path: string, body?: RequestInit["body"], params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
            method,
            body: body ?? null,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}
