import { jsPDF } from "jspdf";
import { fmtNonEmpty } from "./billing";

const ISSUER_NAME = "ABC";
const ISSUER_ADDRESS = "domcekova 16, Praha 5";

export interface InvoicePdfParams {
  invoiceNumber: string;
  jobNumber: string;
  billedPartyName: string;
  billingCurrency: string;
  invoiceType: "breakdown" | "total";
  lineItems: { label: string; amount: number }[];
  totalAmount: number;
}

// Builds an invoice PDF in the browser and triggers a download.
export function generateInvoicePDF(params: InvoicePdfParams): void {
  const { invoiceNumber, jobNumber, billedPartyName, billingCurrency, invoiceType, lineItems, totalAmount } = params;
  const doc = new jsPDF();
  const w = doc.internal.pageSize.getWidth();
  let y = 20;

  // Header
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("INVOICE", 20, y);
  y += 12;

  // Issuer
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text(ISSUER_NAME, 20, y);
  y += 5;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.text(ISSUER_ADDRESS, 20, y);
  y += 8;

  // Invoice details (right side)
  const rightX = 130;
  let ry = 20;
  doc.setFontSize(9);
  const detail = (label: string, value: string) => {
    doc.setFont("helvetica", "bold");
    doc.text(label, rightX, ry);
    doc.setFont("helvetica", "normal");
    doc.text(value, rightX + 35, ry);
    ry += 5;
  };
  detail("Invoice Number:", invoiceNumber);
  detail("Date:", new Date().toLocaleDateString("en-GB"));
  detail("Reference:", jobNumber);
  detail("Currency:", billingCurrency);

  // Billed to
  y += 4;
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.text("Bill To:", 20, y);
  y += 5;
  doc.setFont("helvetica", "normal");
  doc.text(billedPartyName || "—", 20, y);
  y += 10;

  // Separator
  doc.setDrawColor(180);
  doc.line(20, y, w - 20, y);
  y += 6;

  if (invoiceType === "breakdown") {
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.text("Description", 20, y);
    doc.text("Amount", w - 50, y, { align: "right" });
    y += 2;
    doc.line(20, y, w - 20, y);
    y += 5;

    doc.setFont("helvetica", "normal");
    for (const item of lineItems) {
      if (item.amount > 0) {
        doc.text(item.label, 20, y);
        doc.text(`${billingCurrency} ${fmtNonEmpty(item.amount)}`, w - 50, y, { align: "right" });
        y += 5;
      }
    }
  } else {
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.text("Freight and logistics services as per agreement", 20, y);
    y += 8;
  }

  // Total
  y += 4;
  doc.line(w - 80, y, w - 20, y);
  y += 6;
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("TOTAL DUE:", w - 80, y);
  doc.text(`${billingCurrency} ${fmtNonEmpty(totalAmount)}`, w - 20, y, { align: "right" });

  // Placeholders
  const blankLine = "_______________________________________________";
  y += 16;
  doc.setFontSize(8);
  const placeholder = (label: string) => {
    doc.setFont("helvetica", "bold");
    doc.text(label, 20, y);
    doc.setFont("helvetica", "normal");
    doc.text(blankLine, 55, y);
    y += 6;
  };
  placeholder("Payment Terms:");
  placeholder("Bank Details:");
  placeholder("Due Date:");

  // Footer
  doc.setFontSize(7);
  doc.setTextColor(150);
  doc.text(`Generated by Shipment Tracker — ${ISSUER_NAME}`, w / 2, 285, { align: "center" });

  // Blob output + download link (works in sandboxed iframes where doc.save is blocked).
  const blobUrl = URL.createObjectURL(doc.output("blob"));
  const link = document.createElement("a");
  link.href = blobUrl;
  link.download = `${invoiceNumber}.pdf`;
  link.target = "_blank";
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  setTimeout(() => URL.revokeObjectURL(blobUrl), 10_000);
}
