CREATE TABLE "shipment" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	"job_number" text NOT NULL,
	"shipper" text DEFAULT '' NOT NULL,
	"consignee" text DEFAULT '' NOT NULL,
	"personal_reference" text DEFAULT '' NOT NULL,
	"container_number" text DEFAULT '' NOT NULL,
	"booking_number" text DEFAULT '' NOT NULL,
	"load_type" text DEFAULT '' NOT NULL,
	"shipping_line" text DEFAULT '' NOT NULL,
	"pol" text DEFAULT '' NOT NULL,
	"pod" text DEFAULT '' NOT NULL,
	"destination" text DEFAULT '' NOT NULL,
	"hs_code" text DEFAULT '' NOT NULL,
	"cargo_description" text DEFAULT '' NOT NULL,
	"house_bol_number" text DEFAULT '' NOT NULL,
	"master_bol_number" text DEFAULT '' NOT NULL,
	"house_bol_type" text DEFAULT '' NOT NULL,
	"master_bol_type" text DEFAULT '' NOT NULL,
	"vessel" text DEFAULT '' NOT NULL,
	"voyage" text DEFAULT '' NOT NULL,
	"pcs" text DEFAULT '' NOT NULL,
	"total_weight_tons" numeric(14, 4),
	"total_volume_cbm" numeric(14, 4),
	"cargo_origin" text DEFAULT '' NOT NULL,
	"country_code" text DEFAULT '' NOT NULL,
	"origin" text DEFAULT '' NOT NULL,
	"estimated_departure" date,
	"estimated_arrival" date,
	"trade_direction" text DEFAULT '' NOT NULL,
	"agent" text DEFAULT '' NOT NULL,
	"incoterm_origin" text DEFAULT '' NOT NULL,
	"incoterm_destination" text DEFAULT '' NOT NULL,
	"commercial_invoice_value" numeric(14, 2),
	"status" text DEFAULT 'active' NOT NULL,
	"customs_status" text DEFAULT '' NOT NULL,
	"master_job_id" uuid,
	"containers" jsonb,
	CONSTRAINT "shipment_job_number_unique" UNIQUE("job_number")
);
--> statement-breakpoint
CREATE INDEX "shipment_created_at_idx" ON "shipment" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "shipment_deleted_at_idx" ON "shipment" USING btree ("deleted_at");--> statement-breakpoint
CREATE INDEX "shipment_job_number_idx" ON "shipment" USING btree ("job_number");